project_id = "rtsjqijwwikgfmwrivnz"

[functions.create-checkout]
verify_jwt = false

[functions.complete-order]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
